[package]
name = "stribog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
glam = "0.30.5"
log = "0.4.27"
rerun = { version = "0.24.0", default-features = false, features = ["sdk"] }
rtlsdr-rs = { path = "./rtl-sdr-rs" }
